### ISSUE TITLE
what if my balance is under the IOTA Foundation Custody

### ISSUE THREAD

**Issue by jellicoe** [rajivshah3/IOTA-Balance-Finder#4]
what if my balance is under the IOTA Foundation Custody - i hacked this script to look at https://gist.githubusercontent.com/cyclux/2bb05d873c4ec6115cad1d100263d489/raw/612a49e46091586957448f6606ea981ab18022e7/snapshot_validation_20171023.txt 

my funds are in there - but this script did not find them

**Comment by iivanov2** [comment]
you cannot get your funds if they are under the IOTA Foundation Custody with a tool, I am not sure if this tool is save, ask on IOTA slack if it some scam or save

**Comment by rajivshah3** [comment]
I can assure you that this is safe. I'm rajivshah in IOTA Slack, DM me if you'd like me to walk you through it with more detail. What this tool does is generates addresses from your seed and checks them against the snapshot txt files. It then looks at the reason your funds are in custody and shows you both the address and reason. It's basically a way to automate the tedious process of attaching an address and looking through the snapshot txt file by hand for all of your addresses.

**Comment by rajivshah3** [comment]
@jellicoe regarding the script not finding your balance, did you transition on August 11?

**Comment by jellicoe** [comment]
no

my transactions are all in the custody file / snapshot
